# Generated by Django 5.2.2 on 2025-06-09 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_small_int', models.PositiveSmallIntegerField(choices=[(1, 'option1'), (2, 'option2')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Table3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_field', models.DurationField()),
                ('emial_field', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integer_field', models.IntegerField(blank=True, null=True)),
                ('float_field', models.FloatField(blank=True, null=True)),
                ('char_field', models.CharField(max_length=15)),
                ('text_field', models.TextField(blank=True)),
                ('boolean_field', models.BooleanField(default=False)),
                ('date_field', models.DateField(blank=True, null=True)),
                ('time_field', models.TimeField(blank=True, null=True)),
                ('datetime_field', models.DateTimeField(blank=True, null=True)),
                ('image_field', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('file_field', models.FileField(blank=True, null=True, upload_to='files/')),
                ('foreign_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table1_foreign', to='rest_basic.table2')),
                ('one_to_one', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table1_one', to='rest_basic.table2')),
                ('many_to_many', models.ManyToManyField(blank=True, related_name='table1_many', to='rest_basic.table3')),
            ],
        ),
    ]
