# Generated by Django 5.2.2 on 2025-06-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table3',
            old_name='emial_field',
            new_name='email_field',
        ),
    ]
